services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo:latest
    container_name: demo
    ports:
      - "${APP_HTTP_PORT:-8080}:8080"
    environment:
      APP_HTTP_PORT: "${APP_HTTP_PORT:-8080}"
#      DB_URL: "${DB_URL:-}"
#      DB_USERNAME: "${DB_USERNAME:-}"
#      DB_PASSWORD: "${DB_PASSWORD:-}"
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      JAVA_OPTS: "${JAVA_OPTS:-}"
    restart: unless-stopped
    volumes:
      - ./logs:/usr/app/logs
    env_file:
       - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

